#!/usr/bin/env sh

# Pre-push hook temporarily disabled until turbo/SWC issue is resolved
# A non-blocking hook provides false confidence - better to disable entirely

# TODO: Re-enable when build issues are fixed
# npm run build

# TODO: Uncomment when tests are added
# npm test
